'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Icon } from '@iconify/react';
import "./globals.css";
import "./globalicon.css";
import "bootstrap/dist/css/bootstrap.min.css";

import "./mainstyle.scss";

import ToastProvider from "./libs/ToastProvider";

import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from "react-toastify";
import { Toaster } from 'react-hot-toast';
import { useEffect } from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Talent Xpert",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (typeof document !== 'undefined') {
      import('bootstrap/dist/js/bootstrap.bundle.min.js')
    }
  }, [])
  
  return (
    <html lang="en">
      <body className={inter.className}>
        
            {children}
        
      </body>
    </html>
  );
}
